setup localization
wahid-d/durgerking pull request #68
Opened 2023-07-18 09:25 UTC by tparizoda

Close #52

2023-07-18 14:16 UTC, wahid-d requested changes
Button lar uchun ham bitta bo'sh class yharating va reurslarini yaratib qo'yingl Keyin uni localizerini ham scope ichida initialize qiling

buttonLocalizer = scope.ServiceProvider....

2023-07-18 14:16 UTC, wahid-d commented on Program.cs
> +builder.Services.AddControllers();
AddControllers pastda turibdiku

2023-07-18 14:16 UTC, wahid-d commented on Services/UpdateHandler.Message.cs
> +                new KeyboardButton[] { "Orders 📝" },
bu nega?

2023-07-18 14:16 UTC, wahid-d commented on Services/UpdateHandler.Message.cs
> +
bu nega?

2023-07-18 14:16 UTC, wahid-d commented on Services/UpdateHandler.cs
> +        localizerFactory.Create(typeof(Resources.Message));
bu kerak emas

2023-07-18 14:16 UTC, wahid-d commented on Services/UpdateHandler.cs
> +        IStringLocalizerFactory localizerFactory)
bu ikkovi ham kerak emas

2023-07-18 14:16 UTC, wahid-d commented on Services/UpdateHandler.cs
> +        IStringLocalizerFactory localizerFactory)
bu kerak emas

2023-07-19 15:06 UTC, tparizoda commented on Program.cs
> -
ozimni branchimda yog ekan

2023-07-19 22:09 UTC, wahid-d approved these changes

2023-07-19 22:09 UTC, merged